default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: kelasin_backend_dev

test:
  <<: *default
  database: kelasin_backend_test

production:
  <<: *default
  connects_to:
    database:
      primary:
        <<: *default
        database: kelasin_backend
      cache:
        <<: *default
        database: kelasin_cache
      cable:
        <<: *default
        database: kelasin_cable
